### ISSUE TITLE
unroll_videos(force=True) deletes the mp4 files before unrolling

### ISSUE THREAD

**Issue by cagcoach** [bonn-activity-maps/aikapi#16]
When I have the filetree accoring to the [paper](https://cg.cs.uni-bonn.de/aigaion2root/attachments/bonn_activity_maps_arxiv.pdf), s.th the videos are in `[dataset]\videos\cameraXX\recording.mp4`, `unroll_videos(force=True)` would delete the videos folder before unrolling and thus all the recordings.

Without force it just says: `The image format is different from the unrolled frames. If you want to unroll them again and overwrite the current frames, please use the option force=True`

**Comment by jutanke** [comment]
c22a9f2

**Comment by jutanke** [comment]
Can this issue be closed @beapc18 ?

**Comment by beapc18** [comment]
The structure of the dataset is described in the [readme](https://github.com/bonn-activity-maps/aikapi/blob/master/README.md). If it is structured that way, there should be no problem.
