### ISSUE TITLE
Unroll mp4

### ISSUE THREAD

**Issue by jutanke** [bonn-activity-maps/aikapi#2]
We need to unroll the videos into images (using ffmpeg)

**Comment by almartmen** [comment]
.png or .jpg flag for the unroll.

**Comment by jutanke** [comment]
this could be a parameter but should default to png

**Comment by almartmen** [comment]
Independent python script that should be executed at the beginning. Could also be a method of the API but we should provide a script to do it directly.

**Comment by jutanke** [comment]
This method should unroll using "lazy" loading, e.g. it might happen that someone is interested ONLY in the 3D poses and not in the videos. For this, the videos do not have to be unrolled (which would also consume a lot of disk space). Instead, this method should be triggered the first time access to an image is being made (or manually by a user).

As output format for the images we should default to ```png``` which should preserve the video quality. As an alternative, if someone triggers the function manually, we can have a ```jpg``` output but the quality level should be high, e.g. ```-qscale:v 2```
