### ISSUE TITLE
Question about frame number

### ISSUE THREAD

**Issue by sj-li** [bonn-activity-maps/aikapi#8]
Hi:

When I use a for loop to detect the frame number of split 181129, the number that report an error (129724) is much larger than aik.get_total_frames() gives (64863).

```
dataset_name = '181129' 

aik = AIK(dataset_dir, dataset_name, image_format='png')

frames = aik.get_total_frames()

person_ids = aik.get_person_ids()

for t in range(200000):
    for i in person_ids:
        print(t, frames)
        line = aik.get_person_in_frame(t, i) 

```

Which one is correct?

Best

**Comment by jutanke** [comment]
@beapc18 what value is returned for ```get_total_frames```? Is this already taking into account the downsampling of x2? Please note that the end user should NOT work with the downsampled dataset but with the full data

**Comment by beapc18** [comment]
It wasn't taking into account the downsampling, it should be fixed now. 
But there is still an error, the last valid frame in the dataset.json is 64863 and the last frame of the dataset is 64862. The same applies to dataset 190719

**Comment by jutanke** [comment]
Hm, this is an error in the export script on the annotation tool then, is it not? @beapc18

**Comment by sj-li** [comment]
Emm, the returned value still not correct.
For 181129, get_total_frames() returns 129726, but 129724 is the maximum value that will not report a bug.

test program:

```

frames = aik.get_total_frames()
person_ids = aik.get_person_ids()

for i in person_ids:
    for t in range(frames):
        print(t, i)
        line = aik.get_person_in_frame(t, i)


```

**Comment by jutanke** [comment]
https://github.com/bonn-activity-maps/aikapi/commit/43542b29cd61e43c5e55c8c337cecb8d80e05cc3#commitcomment-43305792
@beapc18 due to the downsampling, you can be off 1 or 2 frames. Please make sure for each dataset that the last valid frame calculated is in fact actually the last valid frame

**Comment by beapc18** [comment]
The total number of frames should be correct now

**Comment by jutanke** [comment]
Can we close this issue?

**Comment by sj-li** [comment]
sure :)
